name: ${project.name}
main: de.jeter.chatex.ChatEx
version: ${project.version}
authors: [ Jeter, Wizard_x ]
description: Sohbet yönetimi eklentisi
softdepend: [ LuckPerms, Vault, PlaceholderAPI, Essentials ]
api-version: 1.13

commands:
  chatex:
    description: ChatEx Eklentisi komutları

permissions:
  chatex.allowchat:
    description: Sohbete izin verir
    default: true
  chatex.chat.global:
    description: Genel sohbeti (menzilli mod etkinse) veya Çapraz sunucu sohbetini kullanmak için gereklidir
    default: false
  chatex.chat.color:
    description: Sohbette & ile renk kodlarını kullanmak gerekir
    default: false
  chatex.antispam.bypass:
    description: Antispam sistemini atlamak gerekiyor
    default: false
  chatex.bypassads:
    description: AdBlocker'ı atlamak için gereklidir
    default: false
  chatex.notifyad:
    description: Bir oyuncu reklam vermeye çalıştığında mesaj gönderilmesi gerekir.
    default: false
  chatex.notifyupdate:
    description: Katıldığınızda yeni güncellemeler hakkında bildirim almak için gereklidir
    default: false
  chatex.clear:
    description: Sohbeti temizlemek için /chatex clear kullanmanız gerekir
    default: op
  chatex.reload:
    description: Chatex'in yapılandırmasını ve mesajlarını yeniden yüklemek için /chatex reload komutunu kullanmak gerekir.
    default: op
